// This file was automatically generated by informer-gen

package v1alpha1

import (
	ds_v1alpha1 "github.com/ForgeRock/dsoperator/pkg/apis/ds/v1alpha1"
	versioned "github.com/ForgeRock/dsoperator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/ForgeRock/dsoperator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/ForgeRock/dsoperator/pkg/client/listers/ds/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// DirectoryServiceInformer provides access to a shared informer and lister for
// DirectoryServices.
type DirectoryServiceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.DirectoryServiceLister
}

type directoryServiceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDirectoryServiceInformer constructs a new informer for DirectoryService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDirectoryServiceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDirectoryServiceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDirectoryServiceInformer constructs a new informer for DirectoryService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDirectoryServiceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DsV1alpha1().DirectoryServices(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DsV1alpha1().DirectoryServices(namespace).Watch(options)
			},
		},
		&ds_v1alpha1.DirectoryService{},
		resyncPeriod,
		indexers,
	)
}

func (f *directoryServiceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDirectoryServiceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *directoryServiceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&ds_v1alpha1.DirectoryService{}, f.defaultInformer)
}

func (f *directoryServiceInformer) Lister() v1alpha1.DirectoryServiceLister {
	return v1alpha1.NewDirectoryServiceLister(f.Informer().GetIndexer())
}
