// This file was automatically generated by lister-gen

package v1alpha1

// DirectoryServiceListerExpansion allows custom methods to be added to
// DirectoryServiceLister.
type DirectoryServiceListerExpansion interface{}

// DirectoryServiceNamespaceListerExpansion allows custom methods to be added to
// DirectoryServiceNamespaceLister.
type DirectoryServiceNamespaceListerExpansion interface{}
